apiVersion: v1
kind: Service
metadata:
  name: spin-deck-external
  namespace: spinnaker
  annotations:
    service.beta.kubernetes.io/docker-desktop-load-balancer: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: "127.0.0.1"
  ports:
    - port: 9999
      targetPort: 9000
      protocol: TCP
      name: http
  selector:
    app: spin-deck
---
apiVersion: v1
kind: Service
metadata:
  name: spin-gate-external
  namespace: spinnaker
  annotations:
    service.beta.kubernetes.io/docker-desktop-load-balancer: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: "127.0.0.1"
  ports:
    - port: 8084
      targetPort: 8084
      protocol: TCP
      name: http
  selector:
    app: spin-gate 